services:

  app:
    env_file: .env
    image: 'gutapp:latest' # image name we're giving.
    build:
     context: ${DOCKERFILE} #docker file gives the build context.
    container_name: gutapp
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:80"

  db:
    image: 'postgres:17' # image we're depending on since we're using postgres 17 in instance
    container_name: gutapp_db # name of container created based on image.
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: # local postgres port and host port.
      - "5432:80"