// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZ0LVWlKEcx7Vsp5MskDKqdyVx7DLu-Y',
    appId: '1:231567506435:web:14be1e66b5508868d62236',
    messagingSenderId: '231567506435',
    projectId: 'guthealth-6e95b',
    authDomain: 'guthealth-6e95b.firebaseapp.com',
    storageBucket: 'guthealth-6e95b.firebasestorage.app',
    measurementId: 'G-5ZQKWV9XKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOxOos3J9MJdbL-YDOu6smKfAzqfJe2M',
    appId: '1:231567506435:android:cb3b9d952de0bbbdd62236',
    messagingSenderId: '231567506435',
    projectId: 'guthealth-6e95b',
    storageBucket: 'guthealth-6e95b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVldqJDHaSDrb4_gMTUf3ihokv5GxRWeQ',
    appId: '1:231567506435:ios:50480de3241b93a6d62236',
    messagingSenderId: '231567506435',
    projectId: 'guthealth-6e95b',
    storageBucket: 'guthealth-6e95b.firebasestorage.app',
    iosBundleId: 'com.example.guthealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVldqJDHaSDrb4_gMTUf3ihokv5GxRWeQ',
    appId: '1:231567506435:ios:50480de3241b93a6d62236',
    messagingSenderId: '231567506435',
    projectId: 'guthealth-6e95b',
    storageBucket: 'guthealth-6e95b.firebasestorage.app',
    iosBundleId: 'com.example.guthealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZ0LVWlKEcx7Vsp5MskDKqdyVx7DLu-Y',
    appId: '1:231567506435:web:9833225c72d82cbdd62236',
    messagingSenderId: '231567506435',
    projectId: 'guthealth-6e95b',
    authDomain: 'guthealth-6e95b.firebaseapp.com',
    storageBucket: 'guthealth-6e95b.firebasestorage.app',
    measurementId: 'G-VEL35DMNFP',
  );
}
