name: Feature Request
description: Request a new feature.
title: "[FEATURE]: "
labels: ["enhancement"]
projects: ["spe-uob/2025-GutHealthMonitoringApp"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a feature request form for Gut Health Monitoring App. To help us understand and implement your feature request, please fill out the following information.
  - type: markdown
    attributes:
      value: |
        Please add all relevant issue metadata to your issue. This includes all relevant: assignees, labels, milestone and relevant branches/pull requests. 
  - type: dropdown
    id: subproject-type
    attributes:
      label: Sub-project
      description: Which sub-project would this feature be implemented in?
      options:
        - GHA Survey (`gha-survey`)
        - GHA MoodLog (`gha-moodlog`)
        - GHA FoodLog (`gha-foodlog`)
        - GHA Recipe (`gha-recipe`)
        - GHA General (`gha-general`)
      multiple: true
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature is.
      placeholder: Describe the feature here.
    validations:
      required: true
